### PR TITLE
New temporal matching/collocation implementation

### PR DESCRIPTION
**Pull request by s-scherrer**
This contains a new implementation of temporal matching/collocation, as discussed in #176.

It uses ``pd.reindex`` for matching with nearest neighbours, as was done in `smecv`. I added a method keyword, so different collocation/interpolation methods can be implemented in the future, if necessary.

### CODE REVIEW

**Comment by s-scherrer** [comment]
This is the error in CI:

```
failed
Pip subprocess error:
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-install-fd4lpj1t\\ismn_91ccbc45032e405c96f1207e7ea7b342\\tests/test_data/Data_seperate_files_header_20170810_20180809/COSMOS/Barrow-ARM/COSMOS_COSMOS_Barrow-ARM_sm_0.000000_0.210000_Cosmic-ray-Probe_20170810_20180809.stm'
CondaEnvException: Pip failed
Command exited with code 1
```

Is this related to my changes?

**Comment by wpreimes** [comment]
> 
> 
> This is the error in CI:
> 
> ```
> failed
> Pip subprocess error:
> ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-install-fd4lpj1t\\ismn_91ccbc45032e405c96f1207e7ea7b342\\tests/test_data/Data_seperate_files_header_20170810_20180809/COSMOS/Barrow-ARM/COSMOS_COSMOS_Barrow-ARM_sm_0.000000_0.210000_Cosmic-ray-Probe_20170810_20180809.stm'
> CondaEnvException: Pip failed
> Command exited with code 1
> ```
> 
> Is this related to my changes?

probably not, as it is also in #205 .

**Comment by s-scherrer** [comment]
```
'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-install-fd4lpj1t\\ismn_91ccbc45032e405c96f1207e7ea7b342\\tests/test_data/Data_seperate_files_header_20170810_20180809/COSMOS/Barrow-ARM/COSMOS_COSMOS_Barrow-ARM_sm_0.000000_0.210000_Cosmic-ray-Probe_20170810_20180809.stm'
```

I assume this filename is too long, it's 261 characters, if I remember correctly Windows has a limit of 255 characters.

**Comment by wpreimes** [comment]
> COSMOS_COSMOS_Barrow-ARM_sm_0.000000_0.210000_Cosmic-ray-Probe_20170810_20180809.stm

yeah, sounds reasonable. Ok so this is nothing related to pytesmo

**Review by sebhahn — APPROVED** [review]
Looks good to me!

**Pull request merged**
