### PR TITLE
Only raise warning when not enough data for bootstrapping

### PR DESCRIPTION
**Pull request by s-scherrer**
I changed the bootstrapping functions to warn and return NaN for the confidence intervals instead of raising an error when there is not enough data to do bootstrapping, as discussed in #251

### CODE REVIEW

**Comment by s-scherrer** [comment]
This issue again:

```
  File "/usr/share/miniconda3/envs/pytesmo/bin/pytest", line 8 in <module>
tests/test_validation_framework/test_validation.py::test_ascat_ismn_validation_metadata_rolling 
/home/runner/work/_temp/2c06d129-8349-4c2d-a0df-7358a0b65a24.sh: line 4:  4925 Segmentation fault      (core dumped) pytest --cache-clear -m 'full_framework'
```

I think it's unrelated to my changes, since the tests run on 3.7, but I thought that running the full_framework tests separately solved the issue.

**Comment by wpreimes** [comment]
> This issue again:
> 
> ```
>   File "/usr/share/miniconda3/envs/pytesmo/bin/pytest", line 8 in <module>
> tests/test_validation_framework/test_validation.py::test_ascat_ismn_validation_metadata_rolling 
> /home/runner/work/_temp/2c06d129-8349-4c2d-a0df-7358a0b65a24.sh: line 4:  4925 Segmentation fault      (core dumped) pytest --cache-clear -m 'full_framework'
> ```
> 
> I think it's unrelated to my changes, since the tests run on 3.7, but I thought that running the full_framework tests separately solved the issue.

I think it did ... until a few weeks ago. I will take a look at this today and try to fix it.

**Comment by wpreimes** [comment]
btw, the reason why I have not merge this yet is that I should implement an option into the validation framework that allows a user to skip points where an error during metric calculation occurred.
E.g. An option to continue on errors in this loop: https://github.com/TUW-GEO/pytesmo/blob/master/src/pytesmo/validation_framework/validation.py#L239
In that case it would be fine if the Bootstrapping metrics are only calculated when the bootstrapping is possible (which would be more consistent, otherwise we have more points where the metric was calculated than points where the CI was calculated), right?

**Comment by s-scherrer** [comment]
Right, that's probably the better solution, I didn't think of this before. Let's add the error handling in this loop then.

**Pull request closed without merging**
