### PR TITLE
copy mask in resample_to_grid(), thus preventing it to get modified during iterations

### PR DESCRIPTION
**Pull request by Lmoesinger**
**Issue:** Currently `mask` is used to generate a masked array each loop. However, if `data` in 270: `output_array[~mask] = data` contains nan values, the mask of `output array` will change, and by extensions also the original `mask`. Therefore in subsequent  loop iterations `mask` will be different.

**Fix:** Just passing a copy of `mask` prevents it from changing between iterations.

### CODE REVIEW

**Comment by cpaulik** [comment]
Would the `hard_mask` keyword also solve it? See https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ma.array.html#numpy.ma.array

**Comment by Lmoesinger** [comment]
I think it would in my case (cant check right now), but this alters the properties of `output_data`, and therefore could cause problems for projects that are already using this function.

**Comment by cpaulik** [comment]
We can always call `soften_mask` on the output masked arrays to make them the same as they are now. 

In any case. Do you have a small testcase that we could include that illustrates the problem. Since this is such a hidden thing a test would be nice.

**Comment by Lmoesinger** [comment]
I had the issue when data was a dict of numpy.ma.arrays. Is the function even meant to work with those, or is the goal to just support standard numpy.arrays?

**Comment by cpaulik** [comment]
The function is defined for normal numpy arrays with all masked data points removed from the data itself and from the coordinate arrays.

If you need to add the data back into a bigger array after resampling then this is best handled outside of this function

**Comment by Lmoesinger** [comment]
hm, i have trouble creating a test that breaks (with or w/o using masked arrays). Anyway, filling them before resampling solves the issue, so im gonna close it since it is not a bug.

A bit offtopic, but in my fork `resample_to_grid()` properly works with masked arrays as far as i can tell. In the master branch the function takes a numpy array but returns a masked array. It would be more intuitive if both input and output have the same class IMHO. Alternatively one could also fill the arrays in `output_data` before returning them, to keep it consistent. But this is a design choice that i leave to you.

**Comment by cpaulik** [comment]
I think this behavior is documented sufficiently in the `fill_value` parameter. If no `fill_value` is given we have no other choice than to return a masked array that the user can then fill however she sees fit.

Thanks anyway for taking a detailed look at the function

**Pull request closed without merging**
