### PR TITLE
Fix bug in indexing when interpolate leapday was set

### PR DESCRIPTION
**Pull request by cpaulik**
If input data is less than 1 year then this failed because it tried to index
days that did not exist

### CODE REVIEW

**Review by wpreimes — APPROVED** [review]
Thanks

**Comment by cpaulik** [comment]
@wpreimes Do you have any plans for a next release. I've seen quite a lot of stuff happening lately.

I fixed this hoping we could make a bugfix release quite soon since this is holding us back. If you don't have any problems with it I can also tag a release so it is not work for you.

**Comment by wpreimes** [comment]
The plan was to go for a release by the end of this week. I would like to run a few validations with the updated metrics first. But if it is really urgent I can also do the release now, and if really necessary we could release another fix this week. @s-scherrer your changes are now all in the master, right?

**Comment by s-scherrer** [comment]
Yes, the PRs I opened are all merged. I'm still working on the updated metrics calculators, but this might take a few more days. Releasing now is fine with me.

**Comment by cpaulik** [comment]
I can also put my commit into a hotfix branch and just release 0.9.1. Then we can do a larger release when you are ready.

**Comment by wpreimes** [comment]
> 
> 
> I can also put my commit into a hotfix branch and just release 0.9.1. Then we can do a larger release when you are ready.

ok, I think thats better. 0.10.1 would be the new version

**Comment by cpaulik** [comment]
Yes. just saw 0.10.1.

I can make that on a `v0.10.x` branch

**Comment by cpaulik** [comment]
Pushed the branch, updated the changelog and will tag as v0.10.1

**Comment by wpreimes** [comment]
the `.whl` are included btw: https://github.com/TUW-GEO/pytesmo/actions/runs/632955582#artifacts . Do you have access to pypi still, or should I upload them?

**Comment by cpaulik** [comment]
Yes. I've seen the new CI pipeline using Github Actions. It's nice.

I've uploaded the windows wheels and the tar.gz file since the linux wheels are not compatible with pypi at the moment. If I understood correctly.

**Comment by wpreimes** [comment]
yes. thanks

**Pull request merged**
